### ISSUE TITLE
Lodash is not up to date.

### ISSUE THREAD

**Issue by jdalton** [jsdelivr/jsdelivr#14477]
Like #14469, #14468, #13280, #12546, it looks like jsdelivr bot has stopped automatically updating Lodash based on tags. What's more surprising is none of the issues I've mentioned have gotten a reply from the jsdelivr maintainers 😕

**Comment by megawac** [comment]
@MartinKolarik @jimaek do you guys know whats up?

**Comment by megawac** [comment]
@MartinKolarik libgrabber has this error for lodash

```
error: uncaughtException: Cannot read property 'length' of null date=Mon Oct 31 2016 22:18:44 GMT+0100 (CET), pid=20528, uid=0, gid=0, cwd=/home/libgrabber/jsdelivr, execPath=/usr/bin/node, version=v4.5.0, argv=[/usr/bin/node, /usr/bin/libgrabber, --jsdelivr-path, /home/libgrabber/jsdelivr, --config, /home/libgrabber/libgrabber.config.json], rss=138113024, heapTotal=111599200, heapUsed=76415624, loadavg=[0.17822265625, 0.3154296875, 0.3125], uptime=3911146, trace=[column=8, file=/usr/lib/node_modules/libgrabber/lib/compare-versions.js, function=module.exports, line=33, method=exports, native=false, column=null, file=null, function=Array.sort, line=null, method=sort, native=true, column=23, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=null, line=15955, method=null, native=false, column=7, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=Function.tap, line=7797, method=tap, native=false, column=28, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=null, line=3899, method=null, native=false, column=21, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=arrayReduce, line=664, method=null, native=false, column=14, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=baseWrapperValue, line=3898, method=null, native=false, column=14, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=LodashWrapper.wrapperValue, line=8084, method=wrapperValue, native=false, column=36, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=LazyWrapper.lazyValue [as value], line=1768, method=lazyValue [as value], native=false, column=25, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=baseWrapperValue, line=3896, method=null, native=false, column=14, file=/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js, function=LodashWrapper.wrapperValue, line=8084, method=wrapperValue, native=false], stack=[TypeError: Cannot read property 'length' of null,     at module.exports (/usr/lib/node_modules/libgrabber/lib/compare-versions.js:33:8),     at Array.sort (native),     at /usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:15955:23,     at Function.tap (/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:7797:7),     at /usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:3899:28,     at arrayReduce (/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:664:21),     at baseWrapperValue (/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:3898:14),     at LodashWrapper.wrapperValue (/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:8084:14),     at LazyWrapper.lazyValue [as value] (/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:1768:36),     at baseWrapperValue (/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:3896:25),     at LodashWrapper.wrapperValue (/usr/lib/node_modules/libgrabber/node_modules/lodash/lodash.js:8084:14)]
```

**Comment by jdalton** [comment]
@MartinKolarik It looks like an issue [here](https://github.com/jsdelivr/libgrabber/blob/a91f7fdecc6aa6b084a2fbad0ca18b014f62d5fe/lib/project.js#L140-L146) with [compareVersions](https://github.com/jsdelivr/libgrabber/blob/master/lib/compare-versions.js) erroring because `ax` is nullish and hitting the [ax.length](https://github.com/jsdelivr/libgrabber/blob/master/lib/compare-versions.js#L33) check.

**Comment by MartinKolarik** [comment]
@jdalton yes, working on this right now.

**Comment by MartinKolarik** [comment]
Fixed, thanks for the report!
https://cdn.jsdelivr.net/lodash/4.16.5/lodash.min.js

**Comment by jdalton** [comment]
Thank you! 🙌 

Do you know if this fixes any of the others (linked at the top).

**Comment by MartinKolarik** [comment]
I thought it would, but it doesn't appear so. Going to check those too.

**Comment by megawac** [comment]
@MartinKolarik did you update the version of libgrabber running on the server?

**Comment by MartinKolarik** [comment]
@megawac yes I updated the files changed in jsdelivr/libgrabber#69 over ssh to debug & fix this asap.

**Comment by megawac** [comment]
sweetness thanks a bunch for the quick turnaround

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage
